version: 2.0

jobs:
  build:
    working_directory: ~/project
    
    docker:
      - image: circleci/python:latest

    steps:
      - checkout:
          path: ~/project

      - run:
          name: Install Dependencies
          command: |
            sudo apt update
            sudo apt install dos2unix
            pip3 install colorama
            pip3 install gitpython

      - run:
          name: Build ðŸ—
          working_directory: ~/project
          command: |
            echo 'export PYTHONPATH=$PWD' >> $BASH_ENV
            source $BASH_ENV

            python3 build/build.py
      - run:
          name: Deploy ðŸš€
          working_directory: ~/project/build
          command: |
            echo 'export COMMIT_MESSAGE=$(git log --format=%B -n 1 $CIRCLE_SHA1)' >> $BASH_ENV
            source $BASH_ENV

            dos2unix deploy.sh
            sudo chmod u+x deploy.sh
            ./deploy.sh